### ISSUE TITLE
[Bug]: Ryuk does not work with podman

### ISSUE THREAD

**Issue by dfioravanti** [testcontainers/testcontainers-go#2264]
### Testcontainers version

0.28

### Using the latest Testcontainers version?

Yes

### Host OS

MacOs

### Host arch

ARM

### Go version

1.22

### Docker version

```shell
Client: Docker Engine - Community
 Version:           25.0.3
 API version:       1.41 (downgraded from 1.44)
 Go version:        go1.21.6
 Git commit:        4debf411d1
 Built:             Tue Feb  6 20:42:40 2024
 OS/Arch:           darwin/arm64
 Context:           default

Server: linux/arm64/fedora-39
 Podman Engine:
  Version:          4.9.0
  APIVersion:       4.9.0
  Arch:             arm64
  BuildTime:        2024-01-24T11:07:09+01:00
  Experimental:     false
  GitCommit:
  GoVersion:        go1.21.6
  KernelVersion:    6.7.4-200.fc39.aarch64
  MinAPIVersion:    4.0.0
  Os:               linux
 Conmon:
  Version:          conmon version 2.1.8, commit:
  Package:          conmon-2.1.8-2.fc39.aarch64
 OCI Runtime (crun):
  Version:          crun version 1.14
commit: 667e6ebd4e2442d39512e63215e79d693d0780aa
rundir: /run/crun
spec: 1.0.0
+SYSTEMD +SELINUX +APPARMOR +CAP +SECCOMP +EBPF +CRIU +LIBKRUN +WASM:wasmedge +YAJL
  Package:          crun-1.14-1.fc39.aarch64
 Engine:
  Version:          4.9.0
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.21.6
  Git commit:
  Built:            Wed Jan 24 11:07:09 2024
  OS/Arch:          linux/arm64
  Experimental:     false
```

### Docker info

```shell
Client: Docker Engine - Community
 Version:    25.0.3
 Context:    default
 Debug Mode: false
 Plugins:

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 1
 Server Version: 4.9.0
 Storage Driver: overlay
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: false
  Using metacopy: true
  Supports shifting: true
  Supports volatile: true
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge macvlan ipvlan
  Log: k8s-file none passthrough journald
 Swarm: inactive
 Runtimes: kata krun runj youki crun crun-wasm ocijail runc runsc
 Default Runtime: crun
 Init Binary:
 containerd version:
 runc version:
 init version:
 Security Options:
  seccomp
   Profile: default
  selinux
 Kernel Version: 6.7.4-200.fc39.aarch64
 Operating System: fedora
 OSType: linux
 Architecture: arm64
 CPUs: 4
 Total Memory: 1.904GiB
 Name: localhost.localdomain
 ID: c9c1ca7e-0a95-4d0d-b573-b82806d74d03
 Docker Root Dir: /var/lib/containers/storage
 Debug Mode: false
 Experimental: true
 Live Restore Enabled: false
 Product License: Apache-2.0

WARNING: No swap limit support
WARNING: No cpu cfs quota support
WARNING: No cpu cfs period support
WARNING: No cpu shares support
WARNING: No cpuset support
WARNING: IPv4 forwarding is disabled
WARNING: bridge-nf-call-iptables is disabled
WARNING: bridge-nf-call-ip6tables is disabled
```

### What happened?

I wanted to switch from docker-desktop to podman as docker provider on MacOs. Everything works but only if I disable ryuk. Otherwise testcontainer crashes at boot up with

```
getting request provider: Error response from daemon: container create: unable to find network with name or ID bridge: network not found: creating reaper failed: failed to create container
```

Any idea how to fix this? I have tried everything that I can google, podman is run as rootful and the socket is correctly configured. Testcontainers with ryuk disabled works as expected but it would be nice if it would just work without requiring disabling it.

### Additional information

I am using this project to trigger the issue in case you want to reproduce: https://github.com/dfioravanti/go-rest

**Comment by godart** [comment]
Running into the same issue.  The test I used to recreate the issue looks like:

```
import (
	"context"
	"testing"

	"github.com/testcontainers/testcontainers-go"
)

func TestPodman(t *testing.T) {
	ctx := context.Background()
	_, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: testcontainers.ContainerRequest{}, // never evaluated ...
	})
	if err != nil {
		t.Fatalf("could not start container: %v", err)
	}
}
``` 
I'd expect it to fail with something hinting towards the image name being empty.

The output is
```
=== RUN   TestPodman
2024/04/17 12:04:54 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 5.0.1
  API Version: 1.41
  Operating System: fedora
  Total Memory: 1952 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: 748e590ad3a32566931082a26236b0bed5703256a2a60b218eb5f4bfd72a9b76
  Test ProcessID: 6986206b-fbed-4e04-8f4e-d2ba49e32112
2024/04/17 12:04:54 🐳 Creating container for image testcontainers/ryuk:0.7.0
    model_test.go:36: could not start container: Error response from daemon: container create: unable to find network with name or ID bridge: network not found: creating reaper failed: failed to create container
--- FAIL: TestPodman (0.09s)
=== RUN   TestPodman
2024/04/17 12:04:54 🐳 Creating container for image testcontainers/ryuk:0.7.0
    podman_testcontainers_test.go:16: could not start container: Error response from daemon: container create: unable to find network with name or ID bridge: network not found: creating reaper failed: failed to create container
--- FAIL: TestPodman (0.01s)


FAIL
```

using Podman 5.0.1 here:

```
~> podman version
Client:       Podman Engine
Version:      5.0.1
API Version:  5.0.1
Go Version:   go1.22.1
Git Commit:   946d055df324e4ed6c1e806b561af4740db4fea9
Built:        Mon Apr  1 13:28:31 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.0.1
API Version:  5.0.1
Go Version:   go1.21.8
Built:        Mon Apr  1 01:00:00 2024
OS/Arch:      linux/arm64
```

**Comment by godart** [comment]
I debugged a bit:

The current auto-detection of Podman looks for "podman.sock" within the socket name. This works with Podman on Linux, but when using `podman-mac-helper` for MacOS, the socket name (on the host) is `/var/run/docker.sock`. (https://github.com/testcontainers/testcontainers-go/blob/main/provider.go#L106)

Setting `ProviderType`  in the test code like this
```
	_, err := testcontainers.GenericContainer(ctx, testcontainers.GenericContainerRequest{
		ContainerRequest: testcontainers.ContainerRequest{}, // never evaluated ...
		ProviderType:     testcontainers.ProviderPodman,
	})
```
fixes the network configuration issue. Also the PR https://github.com/testcontainers/testcontainers-go/pull/1990 addresses this with a global configuration option. However this has been stale for a bit.

Maybe the `/info` or `/version` calls could be scraped to detect the server is actually Podman instead.

**Comment by MadsRC** [comment]
I ran into this issue on a setup similar to the original poster.

@godart, I tried your fix, but I kept running into this issue:
```
2024/05/04 21:42:45 github.com/testcontainers/testcontainers-go - Connected to docker:
  Server Version: 5.0.1
  API Version: 1.41
  Operating System: fedora
  Total Memory: 3622 MB
  Resolved Docker Host: unix:///var/run/docker.sock
  Resolved Docker Socket Path: /var/run/docker.sock
  Test SessionID: f9ea1ec477217d1ab405cd38e21e3a471f5360d6b852712ecd8c286ba9a5f9f2
  Test ProcessID: 9043d990-9cb6-40d3-adf7-ba8d0381a833
2024/05/04 21:42:45 🐳 Creating container for image testcontainers/ryuk:0.7.0
2024/05/04 21:42:45 ✅ Container created: 2b3afd5d2e60
2024/05/04 21:42:45 🐳 Starting container: 2b3afd5d2e60
2024/05/04 21:42:45 ✅ Container started: 2b3afd5d2e60
2024/05/04 21:42:45 🚧 Waiting for container id 2b3afd5d2e60 image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/05/04 21:42:45 container logs (unexpected container status "stopped"):
2024/05/04 19:42:45 Pinging Docker...
panic: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/_ping": dial unix /var/run/docker.sock: connect: permission denied
```

I even tried setting my `DOCKER_HOST` to point to my podman socket with `DOCKER_HOST=unix:///Users/user/.local/share/containers/podman/machine/podman.sock` which got rid of the permissions issue but still yielded an error:

```
2024/05/04 21:56:15 github.com/testcontainers/testcontainers-go - Connected to docker:
  Server Version: 5.0.1
  API Version: 1.41
  Operating System: fedora
  Total Memory: 3622 MB
  Resolved Docker Host: unix:///Users/user/.local/share/containers/podman/machine/podman.sock
  Resolved Docker Socket Path: /Users/user/.local/share/containers/podman/machine/podman.sock
  Test SessionID: 64a4a58cee7888739aebd93541d7a4b0b0200d84a9b10f396a5c4148984f1601
  Test ProcessID: 33aa8c36-5cdb-4b96-8725-b9539ef9c0d3
2024/05/04 21:56:15 🐳 Creating container for image testcontainers/ryuk:0.7.0
--- FAIL: TestWithRedis (0.07s)
    startup_test.go:23: Could not start redis: Error response from daemon: container create: statfs /Users/user/.local/share/containers/podman/machine/podman.sock: operation not supported: creating reaper failed: failed to create container
```

Did you not run into this issue?

**Comment by mohsanabbas** [comment]
We are having similar issues with `colima` and `rancher-desktop`


```sh
    2024/05/09 11:11:09 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.9
  API Version: 1.43
  Operating System: Ubuntu 23.10
  Total Memory: 1895 MB
  Resolved Docker Host: unix:///Users/mohsan.abbas/.colima/default/docker.sock
  Resolved Docker Socket Path: /Users/mohsan.abbas/.colima/default/docker.sock
  Test SessionID: c1729139638928699b678e3fdc7dfff4e56482cc2310ee2358a09f68931641e0
  Test ProcessID: e4f04ff7-5395-48a9-be14-51c54e9af8df
2024/05/09 11:11:09 🐳 Creating container for image testcontainers/ryuk:0.7.0
2024/05/09 11:11:09 ✅ Container created: 114d4680aa73
2024/05/09 11:11:09 🐳 Starting container: 114d4680aa73
2024/05/09 11:11:09 ✅ Container started: 114d4680aa73
2024/05/09 11:11:09 🚧 Waiting for container id 114d4680aa73 image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/05/09 11:11:09 failed accessing container logs: Error response from daemon: No such container: 114d4680aa73b82030172ccfe23cb81d4a7364beb7217e6fb2472cd716b0d055
--- FAIL: TestKafkaIntegration (0.57s)
    kgo_test.go:182: Failed to start Kafka container: Error response from daemon: No such container: 114d4680aa73b82030172ccfe23cb81d4a7364beb7217e6fb2472cd716b0d055: could not start container: creating reaper failed: failed to create container
FAIL

```

**Comment by nicanor-romero** [comment]
Same here, tested with `colima` and `rancher-desktop` and ryuk fails to start (it exits as soon as it is started). Tested same code with Docker Desktop and it works OK.

It fails 95% of the times in my case.

```
2024/05/24 18:03:14 github.com/testcontainers/testcontainers-go - Connected to docker: 
  Server Version: 24.0.7
  API Version: 1.43
  Operating System: Alpine Linux v3.19
  Total Memory: 3917 MB
  Resolved Docker Host: unix:////Users/nicanor.romero/.rd/docker.sock
  Resolved Docker Socket Path: //Users/nicanor.romero/.rd/docker.sock
  Test SessionID: b20e559a2d29b918a349d7787d3b028fed79a1dae056e79c34e679e5e8532320
  Test ProcessID: 7cb791c0-9fce-4843-9459-877e9a87f0a7
2024/05/24 18:03:14 🐳 Creating container for image testcontainers/ryuk:0.7.0
2024/05/24 18:03:14 ✅ Container created: 9784e0df56ac
2024/05/24 18:03:14 🐳 Starting container: 9784e0df56ac
2024/05/24 18:03:14 ✅ Container started: 9784e0df56ac
2024/05/24 18:03:14 🚧 Waiting for container id 9784e0df56ac image: testcontainers/ryuk:0.7.0. Waiting for: &{Port:8080/tcp timeout:<nil> PollInterval:100ms}
2024/05/24 18:03:14 failed accessing container logs: Error response from daemon: No such container: 9784e0df56ace89ed75bf6ff055fdef26c849382c5a69525f95a879f43ecd854
2024/05/24 18:03:14 Could not start redis: Error response from daemon: No such container: 9784e0df56ace89ed75bf6ff055fdef26c849382c5a69525f95a879f43ecd854: could not start container: creating reaper failed: failed to create container
```

I tried changing the version of ryuk but got the same results.

I debugged the process and found it fails [here](https://github.com/testcontainers/testcontainers-go/blob/main/docker.go#L1340-L1351), between the `CreateContainer` and the `Start`.

Tested with the [Quickstart example](https://golang.testcontainers.org/quickstart/#3-spin-up-redis)

**Comment by nicanor-romero** [comment]
I finally tracked my error to something between `v0.13.0` (OK) and `v0.14.0`. Debugging how ryuk containers where created I saw this diff among others:

```diff
"Mounts": [
    {
        "Type": "bind",
-       "Source": "/var/run/docker.sock",
+       "Source": "/Users/nicanor.romero/.colima/docker.sock",
        "Destination": "/var/run/docker.sock",
        "Mode": "",
        "RW": true,
        "Propagation": "rprivate"
    }
],
```

I found 2 fixes (I prefer the first one):

1. Setting `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE` env variable to `/var/run/docker.sock`. I previously tried setting it to colima's docker.sock and it still failed. And keep your `DOCKER_HOST` env variable as `unix:////Users/$USER/.colima/docker.sock` with your particular user.

2. Linking the `/var/run/docker.sock` to colima's docker.sock and removing the `DOCKER_HOST` env variable that was pointing to colima.

```
sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
```

**Comment by mdelapenya** [comment]
> I found 2 fixes (I prefer the first one):
> 
> 1. Setting `TESTCONTAINERS_DOCKER_SOCKET_OVERRIDE` env variable to `/var/run/docker.sock`. I previously tried setting it to colima's docker.sock and it still failed. And keep your `DOCKER_HOST` env variable as `unix:////Users/$USER/.colima/docker.sock` with your particular user.
> 2. Linking the `/var/run/docker.sock` to colima's docker.sock and removing the `DOCKER_HOST` env variable that was pointing to colima.
> 
> ```
> sudo ln -sf $HOME/.colima/default/docker.sock /var/run/docker.sock
> ```

@nicanor-romero :

Option 1 is documented here https://golang.testcontainers.org/features/configuration/#docker-socket-path-detection, as part of the discovery mechanism.

And Option 2 is documented here: https://golang.testcontainers.org/system_requirements/using_colima/

@dfioravanti if you agree, I think we can close this one, but please keep it open if you see it's not resolved with the recent versions of the project.

Thanks!

**Comment by dfioravanti** [comment]
@mdelapenya 

> @dfioravanti if you agree, I think we can close this one, but please keep it open if you see it's not resolved with the recent versions of the project.

I tired again with `0.34` and it is still broken. I tired both 1 and 2 and it does not fix the problem. I still get 
```
failed to start container: generic container: create container: reaper: new reaper: run container: container create: Error response from daemon: container create: unable to find network with name or ID bridge: network not found
```

**Comment by mdelapenya** [comment]
@dfioravanti in your tests, are you setting the Podman provider explicitly? This is required at the moment. With the work in https://github.com/testcontainers/testcontainers-go/pull/2810 that would be way simpler thanks to the support for docker contexts. But we are not there yet

**Comment by mdelapenya** [comment]
@dfioravanti I'm sorry, I responded very quick. It's Ryuk, not your own container the own you are interested in. I suggest you test it with that PR/branch, and verify it works as expected.

**Comment by mdelapenya** [comment]
> It's a bit sad to have to re-install docker just after switching to podman 😅

On our side, it's great that you still want to use testcontainers!

Jokes aside, I need to go back to that PR to test against the latest podman. I recall it worked at that time, but need to double check

**Comment by szuecs** [comment]
Hi! I also tried to run testcontainers with podman. 

- Hardware M2 
- Mac OS: 14.6.1

```
% podman version
Client:        Podman Engine
Version:       5.5.1
API Version:   5.5.1
Go Version:    go1.24.3
Git Commit:    850db76dd78a0641eddb9ee19ee6f60d2c59bcfa
Built:         Thu Jun  5 23:45:52 2025
Build Origin:  pkginstaller
OS/Arch:       darwin/arm64

Server:       Podman Engine
Version:      5.5.1
API Version:  5.5.1
Go Version:   go1.23.9
Git Commit:   850db76dd78a0641eddb9ee19ee6f60d2c59bcfa
Built:        Thu Jun  5 02:00:00 2025
OS/Arch:      linux/arm64
```

No colima running.

https://golang.testcontainers.org/quickstart/#3-spin-up-redis
```
% go test ./
--- FAIL: TestWithRedis (8.32s)
    main_test.go:25: 
                Error Trace:    /Users/sszuecs/tmp/go/testcontainers/main_test.go:25
                Error:          Received unexpected error:
                                create container: reaper: new reaper: run container: container create: Error response from daemon: container create: unable to find network with name or ID bridge: network not found
                Test:           TestWithRedis
FAIL
FAIL    mytest  8.336s
FAIL
```

When I add:
```
		ProviderType:     testcontainers.ProviderPodman,
```
I get:
```
]% go test ./
--- FAIL: TestWithRedis (0.32s)
    main_test.go:27: 
                Error Trace:    /Users/sszuecs/tmp/go/testcontainers/main_test.go:27
                Error:          Received unexpected error:
                                create container: reaper: new reaper: run container: started hook: wait until ready: external check: check target: retries: 0 address: localhost:34333: unexpected container status "stopped": could not start container
                Test:           TestWithRedis
FAIL
FAIL    mytest  0.338s
```

go.mod:
```
go 1.24.3

require (
        github.com/stretchr/testify v1.10.0
        github.com/testcontainers/testcontainers-go v0.37.0
)
```


The only way I found is to disable ryuk, which I would like to run:

```
% cat ~/.testcontainers.properties
ryuk.disabled=true
```

Any ideas?

**Comment by dfioravanti** [comment]
@szuecs, I also just turned off ryuk. Everything else just does not work, maybe the new container layer that apple is providing with the next MacOS will fix this. Otherwise I guess we will have to wait until that rewrite mentioned above happen but considering that the branch is stale by 9 months I am not sure when that will happen

**Comment by szuecs** [comment]
@dfioravanti thanks for the confirmation!

**Comment by mdelapenya** [comment]
> [@szuecs](https://github.com/szuecs), I also just turned off ryuk. Everything else just does not work, maybe the new container layer that apple is providing with the next MacOS will fix this. Otherwise I guess we will have to wait until that rewrite mentioned above happen but considering that the branch is stale by 9 months I am not sure when that will happen

@dfioravanti we are working on https://github.com/docker/go-sdk too, which will help simplifying testcontainers-go, and any Go project managing containers. This library already comes the context support to talk to different container alternatives, and I'm currently building a branch for using the new docker sdk atm. I've tested that SDK locally with podman, colima, orbstack and docker, so even though the branch here is stale for 9 months (my bad), it will be eventually addressed with the usage of the SDK.

**Comment by dfioravanti** [comment]
@mdelapenya thanks for the info, looking forward to the sdk becoming stable

**Comment by dfioravanti** [comment]
I finally figured out something that works, what fixed it for me what the change that I proposed in https://github.com/testcontainers/testcontainers-go/pull/3241 which allows to set the provider for all containers and then

1) Setting the VM to run as root with `podman machine set --rootful`
2) Set in `~/.testcontainers.properties` the line `ryuk.container.privileged=true`

@mdelapenya would it be possible to get the PR reviewed ? I know you are focusing on the SDK and I am really looking forward to it but this is a 3 lines changes that would make the life of everyone on Podman nicer. Thanks a lot for the help

**Comment by dfioravanti** [comment]
Hi @mdelapenya, would it be possible to release 0.39 with the `WithProvider` change? I would make my team life easier. Thanks a lot for the help

**Comment by mdelapenya** [comment]
@dfioravanti I'm back after summer break. I'll get up-to-date in the coming days, and will probably produce a release after that, as we already have some features and fixes in main. Nevertheless, you can always consume the tip of the main branch (of course, in the meantime as a workaround)
